# Numpy의 생성

In [1]:
import numpy as np
array1=np.array([1,2,3])
print(array1)

[1 2 3]


In [2]:
# Numpy의 차원을 나타내는 ndarray
# property - shape, ndim - 괄호를 쓰지 않는 형태의 함수
array1d=np.array([1,2,3])
array2d=np.array([[1,2,3],
                  [4,5,6]])
array3d=np.array([[[1,2,3]],
                 [[11,22,33]]])

In [3]:
print('array1d의 shape:', array1d.shape)
print('array1d는 {0}차원'.format(array1d.ndim))

print('array2d의 shape:', array2d.shape)
print('array2d는 {0}차원'.format(array2d.ndim))

print('array3d의 shape:', array3d.shape)
print('array3d는 {0}차원'.format(array3d.ndim))

array1d의 shape: (3,)
array1d는 1차원
array2d의 shape: (2, 3)
array2d는 2차원
array3d의 shape: (2, 1, 3)
array3d는 3차원


In [6]:
# array의 특징
l1=[1,2,'test']
l2=[1,2,3.3]

array_l1=np.array(l1)
print(array_l1,array_l1.dtype)

array_l2=np.array(l2)
print(array_l2,array_l2.dtype)

['1' '2' 'test'] <U11
[1.  2.  3.3] float64


In [11]:
# array의 데이터 타입 변환
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

[1. 2. 3.] float64
[1 2 3] int32


### ndarray를 편리하게 생성하기
- arange, zeros, ones

In [12]:
# np.arange 함수
sq_array=np.arange(10)  # default :: start=0
print(sq_array)
print(sq_array.dtype, sq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [16]:
# 시작점과 끝점을 지정하여 sq_array 생성
# 자세한 사항은 help 함수를 참조 or ?np.arange
sq_array1=np.arange(start=1,stop=9)
print(sq_array1)
print(sq_array1.dtype, sq_array1.shape)

[1 2 3 4 5 6 7 8]
int32 (8,)


In [19]:
# np.zeros 함수 - tuple 형태로 입력할 것 ***
zero_array=np.zeros((2,3),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0 0]
 [0 0 0]]
int32 (2, 3)


In [20]:
# np.ones 함수 - tuple 형태로 입력할 것 ***
one_array=np.ones((2,3),dtype='int32')
print(one_array)
print(one_array.dtype, one_array.shape)

[[1 1 1]
 [1 1 1]]
int32 (2, 3)


In [22]:
# reshape 함수 - 모양을 변환.. ndarray 변환
# 이 함수는 입력값이 tuple이 아니어도 된다.
zero_array.reshape(3,2)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [29]:
# reshape -2
array1=np.arange(1,5)
print(array1)
array1.reshape(-1,5)

[1 2 3 4 5]


array([[1, 2, 3, 4, 5]])

In [30]:
array1.reshape(5,-1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [32]:
# ?np.reshape

#### 각 차원끼리의 변환 - reshape을 활용

In [34]:
array_1d=np.arange(8)
array_1d.shape

(8,)

In [37]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7])

In [42]:
# 위의 array1d를 array2d로 변환
# 1차원 -> 2차원
array_2d=array_1d.reshape(4,2)  
print(array_2d)
print(array_2d.shape)
print(array_2d.ndim)

# 1차원 -> 3차원
array_3d=array_1d.reshape(2,2,2)  # 2차원
print('\n',array_3d)
print(array_3d.shape)
print(array_3d.ndim)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)
2

 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(2, 2, 2)
3
