# Numpy의 정렬 종류

In [6]:
# Numpy의 sorting advance 버전
# np.sort()
# 원본데이터.sort()  <-원본 변경됨

import numpy as np
import pandas as pd

org_array=np.array([3,1,9,5])
print('원본 array:',org_array)

# np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 반환된 원본 행렬:', org_array)

# 원본데이터.sort()로 정렬
sort_array2=org_array.sort()
print('원본데이터.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('원본데이터.sort() 호출 후 반환된 원본 행렬:', org_array)

원본 array: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 반환된 원본 행렬: [3 1 9 5]
원본데이터.sort() 호출 후 반환된 정렬 행렬: None
원본데이터.sort() 호출 후 반환된 원본 행렬: [1 3 5 9]


In [12]:
# 내림차순
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순 정렬:',sort_array1_desc)

내림차순 정렬: [9 5 3 1]


In [45]:
####### 행방향 및 열방향 정렬 - 이해하기***
array2d=np.array([[8,12],[7,1],[3,4]])
sort_array2d_axis0=np.sort(array2d, axis=0)
print(array2d)
print('row방향으로 정렬\n',sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d, axis=1)
print('col방향으로 정렬\n',sort_array2d_axis1)

[[ 8 12]
 [ 7  1]
 [ 3  4]]
row방향으로 정렬
 [[ 3  1]
 [ 7  4]
 [ 8 12]]
col방향으로 정렬
 [[ 8 12]
 [ 1  7]
 [ 3  4]]


In [22]:
# 행방향 및 열방향 정렬
array2d=np.array([[8,12],[7,1]])
sort_array2d_axis0=np.sort(array2d, axis=0)
print(array2d)
print('row방향으로 정렬\n',sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('col방향으로 정렬\n',sort_array2d_axis1)

[[ 8 12]
 [ 7  1]]
row방향으로 정렬
 [[ 7  1]
 [ 8 12]]
col방향으로 정렬
 [[ 8 12]
 [ 1  7]]


In [28]:
# argsort() - 오름차순/내림차순
org_array=np.array([3,1,9,5])
print('원본 array:',org_array)

sort_indices=np.argsort(org_array)
print(sort_indices)

sort_indices_desc=np.argsort(org_array)[::-1]
print(sort_indices_desc)

원본 array: [3 1 9 5]
[1 0 3 2]
[2 3 0 1]


# 데이터간 변환

In [30]:
# DF, 리스트, 딕셔너리, ndarray 상호 변환

In [35]:
import numpy as np
import pandas as pd

col_name1=['col1']
l1=[1,2,3]

# array1 생성
array1=np.array(l1)
print('array1 shape:', array1.shape)

# 데이터프레임 만들기 - list를 통해
l1_df=pd.DataFrame(l1,columns=col_name1)
print('1차원 list로 만든 df:\n',l1_df)

# 데이터프레임 만들기 - array를 통해
array1_df=pd.DataFrame(array1,columns=col_name1)
print('1차원 array로 만든 df:\n',array1_df)

array1 shape: (3,)
1차원 list로 만든 df:
    col1
0     1
1     2
2     3
1차원 array로 만든 df:
    col1
0     1
1     2
2     3


In [37]:
# 2차원 데이터로 DF생성

col_name2=['col1','col2','col3']

# 2x3 형태의 리스트와 ndarray 생성 후 df로 변환
l2=[[1,2,3],[11,12,13]]

# array2 생성
array2=np.array(l2)
print('array2 shape:', array2.shape)

# 데이터프레임 만들기 - list를 통해
l2_df=pd.DataFrame(l2,columns=col_name2)
print('2차원 list로 만든 df:\n',l2_df)

# 데이터프레임 만들기 - array를 통해
array2_df=pd.DataFrame(array2,columns=col_name2)
print('2차원 array로 만든 df:\n',array2_df)

array2 shape: (2, 3)
2차원 list로 만든 df:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 array로 만든 df:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [61]:
# dict로 DF 만들어보기
# {key:value} 값으로 구성됨..
# key는 문자열 컬럼명, value는 리스트 또는 ndarray로 매핑

dict1={'col1':[1,11],'col2':[2,12],'col3':[3,13]}  # 비관계형 데이터베이스: 행과 열로 구성되어 있지 않음
df_dict=pd.DataFrame(dict1)
print('dict로 만든 df:\n',df_dict)
print(type(df_dict))

dict로 만든 df:
    col1  col2  col3
0     1     2     3
1    11    12    13
<class 'pandas.core.frame.DataFrame'>


In [51]:
# 1. df을 ndarray로 변환
# .values
df_array3=df_dict.values
print(type(df_array3))
print(df_array3.shape)

<class 'numpy.ndarray'>
(2, 3)


In [53]:
# 2. df를 list로 변환
# tolist()
list3=df_dict.values.tolist()  # array 'df_dict.values'를 tolist()로 변환
print('\n df_dict.tolist()의 타입:',type(list3))


 df_dict.tolist()의 타입: <class 'list'>


In [60]:
# 3. df를 dict로 변환
# to_dict('list')
df_dict.to_dict()  # index도 함께 나옴
dict3=df_dict.to_dict('list')
print(type(dict3))
dict3

<class 'dict'>


{'col1': [1, 11], 'col2': [2, 12], 'col3': [3, 13]}