### 넘파이 인덱싱

In [1]:
import numpy as np
array1d=np.arange(1,10)
array2d=array1d.reshape(-1,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# 1. 특정 데이터 추출
print('row=2, col=0','\n',array2d[2,0])
print('row=0, col=2','\n',array2d[0,2])

# 2. slicing indexing
print('row=:1, col=2:3','\n',array2d[0:1,2:3])  # 둘 다 :(슬라이싱)이면 2차원

# 3. fancy indexing
print('array2d[[0,1],1]=>','\n',array2d[[0,1],1])
print('array2d[[0,1],1:2]=>','\n',array2d[[0,1],1:2])

row=2, col=0 
 7
row=0, col=2 
 3
row=:1, col=2:3 
 [[3]]
array2d[[0,1],1]=> 
 [2 5]
array2d[[0,1],1]=> 
 [[2]
 [5]]


### 4. 불리언 인덱싱

In [19]:
# 넘파이의 불리언
array1=np.arange(1,8)
array1[array1<4]

array([1, 2, 3])

In [77]:
# pandas로 불리언 인덱싱
# Data 출처 : https://www.kaggle.com/competitions/titanic/data
import pandas as pd

# 절대 경로 설정
#csv
titan_df=pd.read_csv('C:/Users/ASIA-16/Desktop/Digital_dev/data/titanic/train.csv')

#xlsx
titan_df2=pd.read_excel('C:/Users/ASIA-16/Desktop/Digital_dev/data/titanic/train.xlsx')

In [78]:
titan_df.head(7)

PassengerId  Survived  Pclass            Name  ...          Ticket     Fare  Cabin  Embarked
0            1         0       3  Braund, Mr....  ...       A/5 21171   7.2500    NaN         S
1            2         1       1  Cumings, Mr...  ...        PC 17599  71.2833    C85         C
2            3         1       3  Heikkinen, ...  ...  STON/O2. 31...   7.9250    NaN         S
3            4         1       1  Futrelle, M...  ...          113803  53.1000   C123         S
4            5         0       3  Allen, Mr. ...  ...          373450   8.0500    NaN         S
5            6         0       3  Moran, Mr. ...  ...          330877   8.4583    NaN         Q
6            7         0       1  McCarthy, M...  ...           17463  51.8625    E46         S

[7 rows x 12 columns]

In [26]:
# 몇 개의 행과 열을 볼지 세팅
pd.set_option('display.max_columns',8)  # default 10
pd.set_option('display.max_rows',8)  # default 10
titan_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
..           ...       ...     ...   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  ...            Ticket  \
0                              Braund, Mr. Owen Harris  ...         A/5 21171   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  ...          PC 17599   
2                               Heikkinen, Miss. Laina  ...  STON/O2. 3101282   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  ...            113803   
..                                                 ...  ...               ...   
887                       Graham, Miss. Margaret Edith  ...            112053   
888           Johnston, Miss. Catherine Helen "Carrie"  ...        W./C. 6607   
889                              Behr, Mr. Karl Howell  ...            111369   
890                                Dooley, Mr. Patrick  ...            370376   

        Fare  Cabin  Embarked  
0     7.2500    NaN         S  
1    71.2833    C85         C  
2     7.9250    NaN         S  
3    53.1000   C123         S  
..       ...    ...       ...  
887  30.0000    B42         S  
888  23.4500    NaN         S  
889  30.0000   C148         C  
890   7.7500    NaN         Q  

[891 rows x 12 columns]

In [79]:
# shape 찍기
print('titanic data의 shape:',titan_df.shape)

titanic data의 shape: (891, 12)


In [36]:
# Info와 Describe
titan_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [42]:
# value_counts를 통한 데이터 분석
# 주의점: 원래 1차원의 자료만 분석이 가능했다.

# titan_df.Pclass -> 변수이름에 공백이 있으면 불러와지지 않음
titan_df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [43]:
titan_df[['Pclass']].value_counts()  # 2차원도 불러와짐

Pclass
3         491
1         216
2         184
dtype: int64

In [54]:
# 데이터프레임에 새로운 열을 추가
# 새로운 열 = 새로운 변수 -> 파생변수***
titan_df[['Age_by_0']]=0
titan_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  ... Embarked  Age_by_10  \
0                            Braund, Mr. Owen Harris  ...        S      220.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  ...        C      380.0   
2                             Heikkinen, Miss. Laina  ...        S      260.0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  ...        S      350.0   
4                           Allen, Mr. William Henry  ...        S      350.0   

   family_No  Age_by_0  
0          2         0  
1          2         0  
2          1         0  
3          2         0  
4          1         0  

[5 rows x 15 columns]

In [45]:
titan_df['Age_by_10']=titan_df['Age']*10
titan_df['family_No']=titan_df['SibSp']+titan_df['Parch']+1
titan_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
..           ...       ...     ...   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  ... Embarked  \
0                              Braund, Mr. Owen Harris  ...        S   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  ...        C   
2                               Heikkinen, Miss. Laina  ...        S   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  ...        S   
..                                                 ...  ...      ...   
887                       Graham, Miss. Margaret Edith  ...        S   
888           Johnston, Miss. Catherine Helen "Carrie"  ...        S   
889                              Behr, Mr. Karl Howell  ...        C   
890                                Dooley, Mr. Patrick  ...        Q   

     Age_by_0  Age_by_10  family_No  
0           0      220.0          2  
1           0      380.0          2  
2           0      260.0          1  
3           0      350.0          2  
..        ...        ...        ...  
887         0      190.0          1  
888         0        NaN          4  
889         0      260.0          1  
890         0      320.0          1  

[891 rows x 15 columns]

In [52]:
# 변수 제거
titan_df_rmv=titan_df.drop('Age_by_0',axis=1)  # axis = {행은 0, 열은 1}
titan_df_rmv.head()

In [57]:
# 원본을 삭제할 때 활용하는 파라미터
# inplace 파라미터를 활용:: True/False -> default는 false
titan_df.drop('Age_by_0',axis=1,inplace=True)

In [58]:
titan_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  ... Cabin  Embarked  \
0                            Braund, Mr. Owen Harris  ...   NaN         S   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  ...   C85         C   
2                             Heikkinen, Miss. Laina  ...   NaN         S   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  ...  C123         S   
4                           Allen, Mr. William Henry  ...   NaN         S   

   Age_by_10  family_No  
0      220.0          2  
1      380.0          2  
2      260.0          1  
3      350.0          2  
4      350.0          1  

[5 rows x 14 columns]

In [59]:
# titanic 컬럼 가져오기
titan_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Age_by_10',
       'family_No'],
      dtype='object')

In [62]:
# 제거할 변수들을 선택
titan_df.drop(['Age_by_10','family_No'],axis=1, inplace=True)

In [75]:
titan_df.head()

PassengerId  Survived  Pclass            Name  ...  Ticket     Fare  Cabin  Embarked
3            4         1       1  Futrelle, M...  ...  113803  53.1000   C123         S
4            5         0       3  Allen, Mr. ...  ...  373450   8.0500    NaN         S
5            6         0       3  Moran, Mr. ...  ...  330877   8.4583    NaN         Q
6            7         0       1  McCarthy, M...  ...   17463  51.8625    E46         S
7            8         0       3  Palsson, Ma...  ...  349909  21.0750    NaN         S

[5 rows x 12 columns]

In [65]:
titan_df_rmv.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  ... Cabin  Embarked  \
0                            Braund, Mr. Owen Harris  ...   NaN         S   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  ...   C85         C   
2                             Heikkinen, Miss. Laina  ...   NaN         S   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  ...  C123         S   
4                           Allen, Mr. William Henry  ...   NaN         S   

   Age_by_10  family_No  
0      220.0          2  
1      380.0          2  
2      260.0          1  
3      350.0          2  
4      350.0          1  

[5 rows x 14 columns]

In [66]:
titan_col=titan_df_rmv.columns
titan_df_rmv.drop(titan_col[12:14],axis=1, inplace=True)

In [70]:
titan_df_rmv.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  ...     Fare  Cabin  \
0                            Braund, Mr. Owen Harris  ...   7.2500    NaN   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  ...  71.2833    C85   
2                             Heikkinen, Miss. Laina  ...   7.9250    NaN   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  ...  53.1000   C123   
4                           Allen, Mr. William Henry  ...   8.0500    NaN   

   Embarked  family_No  
0         S          2  
1         C          2  
2         S          1  
3         S          2  
4         S          1  

[5 rows x 13 columns]

In [80]:
# 행을 제거

pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)

print('### before axis 0 drop ###')
print(titan_df.head())

titan_df.drop([0,1,2],axis=0,inplace=True)  # 원본 수정
print('   ')
print('### after axis 0 drop ###')
print(titan_df.head())

### before axis 0 drop ###
   PassengerId  Survived  Pclass            Name  ...          Ticket     Fare  Cabin  Embarked
0            1         0       3  Braund, Mr....  ...       A/5 21171   7.2500    NaN         S
1            2         1       1  Cumings, Mr...  ...        PC 17599  71.2833    C85         C
2            3         1       3  Heikkinen, ...  ...  STON/O2. 31...   7.9250    NaN         S
3            4         1       1  Futrelle, M...  ...          113803  53.1000   C123         S
4            5         0       3  Allen, Mr. ...  ...          373450   8.0500    NaN         S

[5 rows x 12 columns]
   
### after axis 0 drop ###
   PassengerId  Survived  Pclass            Name  ...  Ticket     Fare  Cabin  Embarked
3            4         1       1  Futrelle, M...  ...  113803  53.1000   C123         S
4            5         0       3  Allen, Mr. ...  ...  373450   8.0500    NaN         S
5            6         0       3  Moran, Mr. ...  ...  330877   8.4583    NaN   