In [9]:
import numpy as np

array1 = np.arange(1,9)# 1차원 데이터
array1.reshape(-1,4) # 2차원 데이터로의 변환

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
# 1차원 -> 3차원

array1.reshape(2,2,2) # 3차원의 데이터

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
# 1차원 vs 2차원

print('1차원 데이터:',np.arange(1,9)) # (9,)
print('2차원 데이터:',np.arange(1,9).reshape(1,-1)) # (1,9)

1차원 데이터: [1 2 3 4 5 6 7 8]
2차원 데이터: [[1 2 3 4 5 6 7 8]]


### ndarray의 데이터 셋 인덱싱(indexing) 

1. 특정 데이터 추출

2. 슬라이싱(slicing)

3. 팬시 인덱싱(fancy_indexing)

4. 불리언 인덱싱(Boolean-indexing)

####  1. 특정데이터 추출

In [21]:
# 1~ 9까지의 1차원 ndarray를 생성

array1 = np.arange(start=1, stop=10)
array1
print('array1:', array1)

# index는 0부터 시작하므로 
# array1[2]는 3번째 index위치의 데이터 값을 의미

value = array1[2]
value

print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
<class 'numpy.int32'>


In [28]:
# 위의 array1을 reshape하여 
# 2차원으로 변환
array1d = array1.copy()
array2d = array1d.reshape(-1,3)
print(array2d)

# 1,2,4,9를 인덱싱

print('(row=0, col=0) index 가리키는 값:', array2d[0,0]) 
print('(row=0, col=1) index 가리키는 값:', array2d[0,1]) 
print('(row=1, col=0) index 가리키는 값:', array2d[1,0]) 
print('(row=2, col=2) index 가리키는 값:', array2d[2,2]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


####  2. 슬라이싱(slicing)

In [36]:
# 1차원 데이터
array1d = np.arange(start = 1, stop = 10)
array3 = array1d[0:3]

print(array1d)
print(array1d[:3])
print(array1d[3:])
print(array1d[:])

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [52]:
# 2차원 데이터
array1d
array2d = array1d.reshape(3,3)

print(array2d)

#print('array2d:\n', array2d[0:2,0:2])
# print('array2d:\n', array2d[1:,:])
# print('array2d:\n', array2d[1:3,0:3])
#print('array2d:\n', array2d[:,:]) # 단서 [] 인덱싱 표시를 활용하여 가져오세요.

print('array2d:\n', array2d[:2,0]) 
print('array2d:\n', array2d[:2,0:1]) 


[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d:
 [1 4]
array2d:
 [[1]
 [4]]


#### 3. 팬시 인덱싱(Fancy Indexing)

In [65]:
array1d = np.arange(start = 1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
[[1,2],[1,2,3]] # 1차원

In [72]:
print('array2d[[0,1],2]=>',array2d[[0,1],2]) # 1차원의 2열에 해당하는 데이터
print('array2d[[0,1],0:2]=>','\n',array2d[[0,1],0:2]) # 2차원의 0과 1열에 해당 데이터
print('array2d[[0,1]]=>','\n',array2d[[0,1]]) # 열의 자리가 공란이면 전체 데이터

array2d[[0,1],2]=> [3 6]
array2d[[0,1],0:2]=> 
 [[1 2]
 [4 5]]
array2d[[0,1]]=> 
 [[1 2 3]
 [4 5 6]]


#### 4. 불리언 인덱싱(Boolean Indexing)

In [77]:
array1d = np.arange(1,10)

# 5보다 큰 데이터 호출
array1d[array1d>5] # 변수명[조건식]

array([6, 7, 8, 9])

In [78]:
for i in array1d:
    if i>5:
        print(i)
    else:
        pass

6
7
8
9


In [82]:
# 불리언 자료로 원하는 데이터 호출
array1d[np.array([False, False, False, False, False,  True,  True,  True,  True])]

array([6, 7, 8, 9])

In [85]:
# 위치값으로 - positional indexing
print(array1d)
indexes = np.array([5, 6, 7, 8])
array1d[indexes]

[1 2 3 4 5 6 7 8 9]


array([6, 7, 8, 9])

### 행렬의 정렬 - sort( )와 argsort( )
* 넘파이에서 행렬을 정렬하는 대표적인 방법인 np.sort()와 ndarray.sort(), 그리고 정렬된 행렬의 인덱스를 반환하는 argsort()에 대해서 알아보자.

In [89]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array) # 값을 받음
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 반환된 원본 행렬:', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort() # 값을 받나?
print('ndarray.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('ndarray.sort() 호출 후 반환된 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 반환된 원본 행렬: [3 1 9 5]
ndarray.sort() 호출 후 반환된 정렬 행렬: None
ndarray.sort() 호출 후 반환된 원본 행렬: [1 3 5 9]


In [90]:
# end of file